### ISSUE TITLE
How pass data between fragments

### ISSUE THREAD

**Issue by darwinfrancis** [Zhuinden/simple-stack#102]
I have 2 fragments, say Fragment A and Fragment B. I want to sent a String from Fragment A to Fragment B using Bundle. How can i do that, i cant fins any docs or examples related to that.

**Comment by Zhuinden** [comment]
The approach I do is that you make it a property of the Key (which is Parcelable), and you put the Key into the Fragment's bundle.

That way, you no longer have to mess with the bundle itself, you can do

    SecondKey secondKey = getKey<SecondKey>();
    String myParam = secondKey.myParam();

Which works if

``` java
@AutoValue
public abstract class SecondKey extends BaseKey {
    public abstract String myParam();

    public static SecondKey create(String myParam) {
        return new AutoValue_SecondKey(myParam);
    }

    @Override 
    public Fragment createFragment() {
        return new SecondFragment();
    }
}
```

And you use the `BaseFragment` + `BaseKey` that I use in the samples that I use in the project:

[BaseFragment](https://github.com/Zhuinden/simple-stack/blob/cae76e89b517b778e2eb8275df8f5377bbaf00a8/simple-stack-example-basic-fragment/src/main/java/com/zhuinden/navigationexamplefrag/BaseFragment.java)

[BaseKey](https://github.com/Zhuinden/simple-stack/blob/cae76e89b517b778e2eb8275df8f5377bbaf00a8/simple-stack-example-basic-fragment/src/main/java/com/zhuinden/navigationexamplefrag/BaseKey.java)

--------------------------------

The Kotlin version is slightly simpler:

``` kotlin
fun <T: BaseKey> Fragment.getKey() = arguments?.<T>getParcelable("KEY")

@Parcelize
data class SecondKey(val myParam: String): BaseKey {
    override fun createFragment() = SecondFragment()
}

val secondKey = getKey<SecondKey>();
val myParam = secondKey.myParam;
```

This is just my recommendation of course because it eliminates the need for string constants and the lack of "typedness" for the bundle

**Comment by darwinfrancis** [comment]
Hi Zhuinden,

Thanks for your quick  response with detail code snippet. This works fine.
Please include this sample code in doc o wiki, so that others can easily understand.

Thanks for your awesome library.
