### ISSUE TITLE
How can I persist the state of my backstack and restore it when activity is recreated.

### ISSUE THREAD

**Issue by jd-alexander** [Zhuinden/simple-stack#111]
Greetings, 
awesome library! I haven't started using it as yet but I have a use case where I will need to navigate between multiple fragments in a hierarchial kind of way, possibly making jumps within the history so I might do A to B to C to D. Then navigate from D to B to A. What I wanted to know is if I am doing this in a particular activity and then I need to navigate to a new activity and then navigate back to the activity that has those fragments will the state be retained?

**Comment by Zhuinden** [comment]
Hello

Simple-Stack remembers the active history across config changes and process death, which means that whatever you store in the backstack (by default expected to be `Parcelable`), that *will* survive until the Activity is finished.

Fragments are nice in a way because the FragmentManager does a whole bunch of magic to keep their state alive. But what's worth noting is that the samples typically show removing fragments that are not in the history, so in that case when you do `[A,B,C,D] -> [A,B]` then typically `C,D` are removed, and in case of `[A,B] -> [A]`, then `B` would be removed. When a fragment is removed, then its state is also cleared.

If this is not intended behavior, you can however make a StateChanger that doesn't *remove* [A,B,C,D], just shows/hides them (and `add`s them if they're not in the stack).

Overall, the `Backstack` remembers what you put into it until the app is finished, and FragmenManager is what manages *fragment* state.

**Comment by jd-alexander** [comment]
Thanks for the quick response! Just another question before I close this issue, can the library or the navigation cases be tested in any way using Espresso?

**Comment by jd-alexander** [comment]
Thanks, another question can the keys be created dynamically? The use case I have requires that multiple fragments that are of the same type should be added to the backstack and they would be unique based on a key generated at runtime would that be possible?

**Comment by Zhuinden** [comment]
The samples show where fragment tag is based on the `toString()` method of the key where the key is `data class`. So any additional parameter provided to the key will reflect in the fragment tag, like `SomeScreenKey[id=15]`.

As the key is regular *parcelable data class*, parametrization is possible. All I expect *by default* is that it is parcelable.

Someone asked a while ago what to do if the Key is too complex to be Parcelable, and the trick is that you can provide a `KeyParceler` which turns the class into something Parcelable, so the trick was to [set a custom KeyParceler](https://github.com/Zhuinden/simple-stack/issues/52#issuecomment-320163434).

**Comment by Zhuinden** [comment]
So I would think that considering the only limitation that you have is that your key is a `parcelable data class`, but otherwise you are actually able to freely implement `StateChanger` as you see fit; I'm pretty sure you can achieve whatever behavior you have in mind.

**Comment by Zhuinden** [comment]
Hold on, I didn't actually tell you the answer to the top-most question

> How can I persist the state of my backstack and restore it when activity is recreated?

If you use `BackstackDelegate` and `registerForLifecycleCallbacks` (or call the callbacks yourself), then `onSaveInstanceState` is intercepted with an `ActivityLifecycleCallbacks`, so the state of the Backstack is restored just by filling out the `backstackDelegate.onCreate` call like you can see in the samples.

**Comment by jd-alexander** [comment]
Thanks! Very detailed answer. I am gonna be working with it in a few days so will revisit this when the time comes!

**Comment by Zhuinden** [comment]
Hope you'll enjoy having actual control over your navigation history ;)

If you run into anything weird(?) just ping me as usual.
