### ISSUE TITLE
Default classes/implementations for working with fragments

### ISSUE THREAD

**Issue by jamolkhon** [Zhuinden/simple-stack#124]
Currently we have to copy a few classes from samples for working with fragments. I had to copy these three: FragmentStateChanger, BaseKey and BaseFragment. Can we have some or all of them (maybe in separate artifact) for easier adoption?

**Comment by jamolkhon** [comment]
Oh and also the transition animation xml files too.

**Comment by Zhuinden** [comment]
You're absolutely right; technically way back when I didn't do that in order to avoid adding a dependency on the support libs. 

And a mistake on my end was the assumption that "I'll just make a sample for it and then people can see how it works" (and added related wiki pages), but honestly people prefer ready-made solutions instead of having to put things together, and it makes perfect sense that they do :wink: 

I might do something like this when I finally get myself to break the project into modules and still keep the jitpack publishing working.

Considering now I'm kinda "fighting Nav AAC", it definitely helps to add more out-of-the-box defaults, and make the others (the whole Navigator package) opt-in and optional.

**Comment by Zhuinden** [comment]
Technically with the advent of AndroidX, it'll be safer to depend on that with a newer version, the one tricky thing being that some projects are still on support lib.

**Comment by Zhuinden** [comment]
Now that AndroidX is the norm and support libraries require no support, Simple-Stack no longer depends on any `android.support.*` or `androidx.*` libraries, it should be possible to create a separate artifact that contains the FragmentStateChanger.

After 1.5 years, I mark this critical because people are often put off by having to *see* the FragmentStateChanger, and apparently people don't like to look at it (when they're just learning about simple-stack), are ridden with doubt, and instead add a `NavHostFragment` to their project in hopes that using `popUpToInclusive="true", popUpTo="@id/splash_nav_graph"` results in code that is easier to understand.

Clearly that is not optimal, so I'll have to bite the bullet and join the "bump the AndroidX versions" train.

However, I will avoid setting up modular jitpack publishing as it's much easier for me to just create a new repo for it.

**Comment by Zhuinden** [comment]
Now that AndroidX is the norm and support libraries require no support, Simple-Stack no longer depends on any `android.support.*` or `androidx.*` libraries, it should be possible to create a separate artifact that contains the FragmentStateChanger.

After 1.5 years, I mark this critical because people are often put off by having to *see* the FragmentStateChanger, and apparently people don't like to look at it (when they're just learning about simple-stack), are ridden with doubt, and instead add a `NavHostFragment` to their project in hopes that using `popUpToInclusive="true", popUpTo="@id/splash_nav_graph"` results in code that is easier to understand.

Clearly that is not optimal, so I'll have to bite the bullet and join the "bump the AndroidX versions" train.

However, I will avoid setting up modular jitpack publishing as it's much easier for me to just create a new repo for it.

**Comment by itscorey** [comment]
The same happens with **ViewStateChanger** and **ServiceProvider**. Every time I start a new project that uses **SimpleStack** I'd to import it. 😄 

I particularly do not like **libraries** that has a lot of sub-modules whose you should install into your project.

    lib-core:3.3.3
    lib-ui:3.3.3

**But** it could be useful for **SimpleStack's** users as they'll have support out of the box for a lot of things: **ServiceProvider**, **XYZ**StateChangers. They just need to install what they need.

    simplestack:x.y.z // core + ability to make anything a destination 
   
    // optional
    simplestack:fragment:x.y.z // should be packed with ServiceProvider?
    simplestack:view:x.y.z // should be packed with ServiceProvider?

    // optional 2
    simplestack:ui:x.y.z // [View/Fragment/Whatever]StateChanger

Then probably more people are going to use SimpleStack as it'll be easier to use. 🤔

**Comment by Zhuinden** [comment]
I added `critical` but I can't decide on an API I won't hate. For the safe argument passing to fragments, using inheritance is unavoidable. Also I always need to tweak the FragmentStateChanger a bit, but last time I made the `DefaultViewStateChanger` configurable, it became an abomination.

But looking at the FragmentStateChanger also freaks people out when they look at it, so... at some point I'll just sit down and do *something*... :shrug: 

Tricky thing about a default ServiceProvider is default support for `ScopeKey.Child`.

**Comment by Zhuinden** [comment]
Rejoice!

As after 1.5 years, I actually released `simple-stack-extensions` and now you get to have my extension functions and default stuff for fragment navigation that honestly should have been released as an extension artifact about 1 year ago (or at least when AndroidX became commonplace).

See commit: https://github.com/Zhuinden/simple-stack/commit/dbc3ff12a42fa92ae95d2beba1d306ff2fb1c0ee

See repository: https://github.com/Zhuinden/simple-stack-extensions

Enjoy `DefaultFragmentStateChanger`.
