### ISSUE TITLE
How to handle DialogFragment?

### ISSUE THREAD

**Issue by kakai248** [Zhuinden/simple-stack#127]
Any ideas on how to handle DialogFragments? I'm using the FragmentStateChanger that you have as example.

Ideally it would be as seamless as using a regular fragment. I'm trying to treat these DialogFragments like a regular fragment. With it's own ViewModel and all. However, since we can't handle them with a transaction (we have to call `.show()`), it's not as straightforward.

Thanks

**Comment by Zhuinden** [comment]
The tricky thing is that I generally don't use a Key for dialogs because they innately have a back behavior and are recreated by their parent fragment if you use `setParentFragment(this)` before showing them.

As it would then be a "signal to the state changer that doesn't actually affect the backstack state", it'd be the same as `SystemMessage` in Cicerone which eventually got removed in their 4.0.0:

> Removed SystemMessage command (it's not navigation)

In which case my advice would be to not use simple-stack for the dialog itself, emit an event into a DispatchWorkSubject which is observed for "oh I should be showing a dialog".

We actually have a similar mechanism up handled at Activity level, except it's actually a CommandQueue, and so dialogs are shown there with a separate method `.showBottomSheetDialog` instead of `.backstack.*`.

**Comment by kakai248** [comment]
I followed your advice and didn't put it on the stack.

But I wanted to follow a similar pattern so I defined a DialogScreen (equivalent to a key) and created a DialogManager that receives this DialogScreen and the caller fragment (to use target fragment). 

It works, but I'm not satisfied with it. I'm not satisfied with Android navigation in general. We need some straightforward way to do things, not having to hack stuff.

**Comment by Zhuinden** [comment]
The only reason why I didn't consider the use of a dialogkey is because then you have to intercept back in the dialogscreen and then manage it in addition in the state changer that you now have a new type of key; and it's also best if you test it against process death

**Comment by kakai248** [comment]
I see what you mean. But ignoring how Android handles things, a dialog is just a screen with a different layout. It should be able to do everything that a normal screen can do. Including passing values back and stuff like that.

I think that only the dialog screen should know that it's a dialog. The other screens including the one that calls it, should not. 

I'll keep hoping for better view controllers in Android 😢

**Comment by Zhuinden** [comment]
A different layout, but it still requires the view behind it to be active as well - which is not a requirement for regular views. Unless all views are always stacked on top of one another, but that's rather uncommon.

A dialog screen could be handled as a regular screen, but the state changer needs to manage it by hand. And the state changer has to be notified of the back press that happens (or the dismiss, technically).

I presume now that would be easier to do with the BackPressDispatcher.

Dialogs are tricky. I wonder if Composable will help us in the future. Jetpack Navigation is just as tricky with their `<dialog` tag internally, it just comes out of the box.

But I can't do much beyond saying "if dialogs are treated as screens, then this is how it would need to be done". Still trickier than just pretending it's a side-effect of the screen that opens it and belongs to it right there and then, rather than a top-level destination.
