### ISSUE TITLE
Manipulating the backstack from a background thread fails silently 

### ISSUE THREAD

**Issue by kbersztolc** [Zhuinden/simple-stack#141]
Hi,

Thanks for awsome library.

I have an issue with fragment change.
The case is:
After application started I am checking if session is active. If not, user is redirected to login fragment by
`backstack.setHistory(History.single(LoginFragmentKey()), StateChange.REPLACE)`

After this, sometimes fragment won't change any more (restart app solving problem).
I am trying to change fragment via:
`backstack.setHistory(History.single(HomeKey()), StateChange.REPLACE)`

This is rather rare issue but sometimes it happen.
In debugger I am seeing that `queueStateChanges` got `LoginFragmentKey` with status `IN_PROGRESS` and `HomeKey` with status `ENQUEUED`

Please notice that `handleStateChange` callback from `activity` is not called.
Could you help?

**Comment by Zhuinden** [comment]
Is the `completionCallback.stateChangeComplete()` always called?

-----

A common problem that can happen is that


        if (stateChange.topNewState<ViewKey>() == stateChange.topPreviousState()) {
            completionCallback.stateChangeComplete()
            return
        }

is missing.

If you can share your `handleStateChange` method, I can look at it.

**Comment by Zhuinden** [comment]
ok so this looks totally ok, which means the error is elsewhere. However having the changes enqueued but "nothing happens" can only happen if the completion callback is not called, or there is no state changer to start the next state change with.

So:

1.) which type of integration are you using, `Navigator.configure().setStateChanger(this)./*...*/.install(...);`, or `backstackDelegate`?

2.) If `BackstackDelegate`, then are you using `registerForLifecycleCallbacks`, or manually invoke the callback methods?

3.) Are you returning `backstackDelegate.onRetainCustomNonConfigurationInstance()` in the appropriate method?

if it is possible, it's best if you show the whole integration part.

Theoretically if a state change gets stuck, then `onDestroy` of Activity calls `backstackDelegate.onDestroy()`, which in turn is calling to `backstack.executePendingStateChange()`.
 So it should be *impossible* for anything to get stuck.

**Comment by Zhuinden** [comment]
Theoretically I'd think this can happen if the state changer is not set properly

**Comment by Zhuinden** [comment]
`onRetainCustomNonConfigurationInstance()` is matched with `getLastCustomNonConfigurationInstance()`, but in your sample you seem to have `lastNonConfigurationInstance` instead of lastCustomNonConfigurationInstance`. Theoretically it should show an `IllegalArgumentException` if that happens on config change....

> In "frozen" scenario even back does not work (Backstack goBack() method returns true from isStateChangePending()). stateChanger is not null.

Theoretically this shouldn't be possible...  it can theoretically only happen if a PendingStateChange is dispatched (aka `hasStateChanger() && !queuedStateChanges.isEmpty`), but the StateChanger never calls `completionCallback.stateChangeComplete()`. 

In the unlikely-but-not-impossible scenario that this happens across configuration changes (For example, the state changer adds an `onPreDraw` listener to a View, but the View is destroyed before it'd be called), `onDestroy` calls `executePendingStateChange()` on the `Backstack` to force the current "in progress" state change to become completed, and generally in that case StateChanger is removed (as it is auto-removed in onPause) and so the next state change will be "enqueued" when `setStateChanger` is called after config change.

I've used Simple-Stack in production before and this never happened since 0.9.3. 😞 I might need to ask for a sample project and steps to see when it can happen.

**Comment by kbersztolc** [comment]
I think that I found why problem happens. 
I was calling `logout()` from `OkHttp Interceptor` when session expired. It runs on `background thread`.
After fixing this I will observe process.

Thank you for your valuable help.

**Comment by Zhuinden** [comment]
... Ah... I haven't tested thread-safety, so it's safe to say it probably doesn't work as expected if called from background thread. All backstack stuff should be done on main thread or you'll get inconsistent results.

**Comment by Zhuinden** [comment]
Next version will throw exception if Backstack is accessed for writing from wrong thread.

**Comment by Zhuinden** [comment]
With 1.13.2 you can no longer silently run into threading issues, because if the Backstack is touched from a different thread than it was created then it will EXPLODE :boom: 

Ah the good tricks you learn from Realm :smile:

**Comment by Zhuinden** [comment]
Imagine that I caught some multi-threading bug with this 1 year later when I swapped out some custom navigator (that was not working correctly) for simple-stack (which was indeed working correctly).

Your bug report has saved us from a lot of headaches ❤️
