### ISSUE TITLE
Calling backstackManager.finalizeScopes() twice results in an unexpected error message

### ISSUE THREAD

**Issue by jamolkhon** [Zhuinden/simple-stack#150]
I'm getting the error: `The previous scope should exist, but it doesn't! This shouldn't happen. If you see this error, this functionality is broken`.

-----

I'm not sure if it's a bug or a misconfiguration on my side.

Here's my **RootActivity.kt**:

```
class RootActivity : AppCompatActivity(), StateChanger {

  val backstackDelegate = BackstackDelegate(this)
  private val backstack by lazy { backstackDelegate.backstack }
  private val appComponent by lazy { (application as App).appComponent }
  private val stateChanger = FragmentStateChanger(supportFragmentManager, R.id.container)

  override fun onCreate(savedInstanceState: Bundle?) {
    backstackDelegate.setScopedServices(this, ScopeConfiguration(appComponent))
    backstackDelegate.onCreate(savedInstanceState, lastCustomNonConfigurationInstance,
        History.of(AuthKey()))
    backstackDelegate.registerForLifecycleCallbacks(this)

    super.onCreate(savedInstanceState)
    setContentView(R.layout.activity_root)

    backstackDelegate.setStateChanger(this)
  }

  override fun onPostResume() {
    super.onPostResume()
    backstackDelegate.onPostResume()
  }

  override fun onPause() {
    super.onPause()
    backstackDelegate.onPause()
  }

  override fun onDestroy() {
    super.onDestroy()
    backstackDelegate.onDestroy()
  }

  override fun onSaveInstanceState(outState: Bundle?) {
    super.onSaveInstanceState(outState)
    if (outState != null) {
      backstackDelegate.onSaveInstanceState(outState)
    }
  }

  override fun onRetainCustomNonConfigurationInstance(): Any =
      backstackDelegate.onRetainCustomNonConfigurationInstance()

  override fun onBackPressed() {
    if (!backstackDelegate.onBackPressed()) {
      super.onBackPressed()
    }
  }

  override fun handleStateChange(stateChange: StateChange, completionCallback: StateChanger.Callback) {
    if (stateChange.topNewState<Any>() == stateChange.topPreviousState()) {
      // no-op
      completionCallback.stateChangeComplete()
      return
    }

    stateChanger.handleStateChange(stateChange)
    completionCallback.stateChangeComplete()
  }

  fun navigateTo(key: BaseKey) {
    backstack.goTo(key)
  }
}

fun Fragment.navigateTo(key: BaseKey) {
  if (activity is RootActivity) {
    (activity as RootActivity).navigateTo(key)
    return
  }
  throw RuntimeException("I'm not your parent")
}

inline fun <reified T> Fragment.lookup(serviceTag: String = T::class.java.name): T {
  if (activity is RootActivity) {
    return (activity as RootActivity).backstackDelegate.lookupService(serviceTag)
  }
  throw RuntimeException("I'm not your parent")
}

inline fun <reified T> ScopedServices.ServiceBinder.addService(service: T,
    serviceTag: String = T::class.java.name) {
  add(serviceTag, service as Any)
}
```

**AuthKey.kt**:

```
//@Parcelize // not working :(
data class AuthKey(val tag: String = "AuthKey") : BaseKey(), ScopeKey {

  override fun createFragment() = AuthFragment()

  override fun getScopeTag() = AuthScope.SCOPE_TAG

  override fun writeToParcel(dest: Parcel?, flags: Int) {
  }

  override fun describeContents() = 0

  companion object {

    @JvmField
    val CREATOR = object : Parcelable.Creator<AuthKey> {

      override fun createFromParcel(source: Parcel?): AuthKey = AuthKey()

      override fun newArray(size: Int): Array<AuthKey> = emptyArray()
    }
  }
}
```

**AuthScope.kt**:

```
class AuthScope {

  companion object {
    const val AUTH_TAG = "AUTH"
  }
}
```

Inside **AuthFragment.kt** I have this:

`private val controller by lazy { lookup<AuthController>() }`

After pressing back button while on AuthFragment I get the error in the title. The exception happens at line `backstackDelegate.onDestroy()`.

**Comment by jamolkhon** [comment]
Happens on 1.13.1 and 1.13.3

**Comment by Zhuinden** [comment]
I was hoping I'd never see this error message 🤔 

The real question though is why does `Activity.onDestroy()` trigger a `by lazy {` lookup on your side?

**Comment by Zhuinden** [comment]
Theoretically if you need to revert, this seems to be an issue with dispatching `.Activated`, which came in with 1.12.1.

....I really need to know how to reproduce this to proceed, though. I have a bunch of tests, this never happened before. >.<

**Comment by Zhuinden** [comment]
Actually, I have an idea.

Is there ANY chance that for SOME REASON you're calling `backstackDelegate.onDestroy()` twice?

For example, the fact that your sample code seems to register for automatic lifecycle callbacks, AND also invokes `onPause`, `onPostResume`, and most importantly **`onDestroy`** twice?

Triggering `finalizeScopes()` twice can theoretically cause this.

----

I must admit that I didn't think of checking for scope finalization twice, this needs a better error message.

-----

In your app though, the solution is to either remove `registerForLifecycleCallbacks`, or remove calls to `onPause/onPostResume/onSaveInstanceState/onDestroy` because that's what `registerForLifecycleCallbacks` handles internally.

**Comment by jamolkhon** [comment]
Just checked with the scoping sample. The error doesn't happen. However the sample uses Navigator instead of BackstackDelegate. Also it uses explicit scopes I think. Not sure if that matters. I changed to implicit by removing ScopeKey.Child implementation from WordScope. I don't know if that's enough to make it implicit. Sorry, I'm still struggling to understand implicit and explicit scopes.

I'll try to produce a sample later.

**Comment by jamolkhon** [comment]
Yup. Your last comment was right. Dumb me. Issue resolved.

**Comment by jamolkhon** [comment]
A quick question though. Is registerForLifecycleCallbacks equivalent to calling all (required) lifecycle callbacks manually?

**Comment by Zhuinden** [comment]
The only thing I can't track in there are `onCreate` and `onRetainCustomNonConfigurationInstance`.

`onCreate` is too late, and `onRetainCustomNonConfigurationInstance` isn't exposed there so I can't channel into it and therefore still needs to be called.

So it tracks `onPause/onResume/onSaveInstanceState/onDestroy`. I think I have this added to the Javadoc, though.

----------------

> Dumb me.

From my perspective, it's a mistake of my API that I allow this. 🤔 I'll think about what can be done with it, because `registerForLifecycleCallbacks` is a "convenience method", primarily because it's easy to forget for example `onSaveInstanceState` (happened to me before, which is why the method exists...), but `onPostResume` can be useful if simple-stack is used to manage DialogFragments for some reason (and I can only detect `onResume`, but not `onPostResume` from the outside).

--------

Anyways, thanks for finding a bug. You should be getting a reasonable error message when this happens, instead of "hello the world exploded please hold".

**Comment by jamolkhon** [comment]
Sorry another very quick question. I can return the call to registerForLifecycleCallbacks and the missing onCreate and onRetainCustomNonConfigurationInstance I should be good?

**Comment by Zhuinden** [comment]
I had to figure out how I'd want to handle this, especially what to do with scopes after they're finalized; now I'll swallow multiple calls to `finalizeScopes()` in succession as no-op. Scopes also "stop being finalized" when they're triggered to be rebuilt.

So you will no longer get this cryptic error message in 1.13.4.
