### ISSUE TITLE
Backstack for tabs like Instagram or Youtube

### ISSUE THREAD

**Issue by hossein-amini** [Zhuinden/simple-stack#188]
Hi,
I want to create a single Activity application that has a bottom navigation that each tab has its own backstack(like Instagarm or Youtube). Is this library proper for me?
Sorry if I create an issue. I wanted to run sample apps but they didn't build.

Thanks a lot

**Comment by Zhuinden** [comment]
> Sorry if I create an issue. I wanted to run sample apps but they didn't build.

ok, that is odd. The latest versions of Android Studio *should* be able to handle Kotlin Gradle DSL, and it *has* been working for me...

>  has a bottom navigation that each tab has its own backstack(like Instagarm or Youtube). Is this library proper for me?

It *is* technically possible but it's not out-of-the-box behavior. You'd need to use `Backstack` directly and manage them per each tab; and keep track of which backstack is currently selected so that `back` is delegated to the intended backstack.

I did have [a `multistack` sample](https://github.com/Zhuinden/simple-stack/blob/5df5bcab2569bfbf9774f81679c42de83fd9cc71/simple-stack-example-multistack/src/main/java/com/zhuinden/simplestackdemomultistack/util/Multistack.java) but I also haven't touched it in 2 years, and clearly needs an update. :thinking: 

Are you looking to use it with views, or with fragments?

**Comment by hossein-amini** [comment]
Thanks for replying

I tried again but they didn't build. My Android Studio version is 3.4.

> Are you looking to use it with views, or with fragments?

I want to use it with fragments

**Comment by Zhuinden** [comment]
Took longer than it should have, but I've added a multi-stack fragment example.
