### ISSUE TITLE
Ability for scoped services to be initialized independently from state changing

### ISSUE THREAD

**Issue by matejdro** [Zhuinden/simple-stack#212]
While attempting to make scoped-services constructor-injectable, I have noticed an interesting race condition.

[Comment on the sample repo](https://github.com/matejdro/simple-stack-dagger-scoping-sample/blob/8cc8d09af4c72ec579b0e9945885c5c202dbac99/app/src/main/java/com/matejdro/simple_stack_dagger_demo/MainActivity.kt#L41) contains bulk of the explanation plus sample code.

Do you think it would be feasible to somehow separate scoped services initialisation? That way, when using constructor fragment injection, `setStateChanger` would not need to be called on different places depending on whether activity was created from saved state or not.

**Comment by Zhuinden** [comment]
If you're doing this:

https://github.com/matejdro/simple-stack-dagger-scoping-sample/blob/8cc8d09af4c72ec579b0e9945885c5c202dbac99/app/src/main/java/com/zhuinden/simplestack/navigator/BackstackActivity.kt#L51-L70

Then you don't need to use `Navigator`. As this is what `Navigator` is trying to do for you behind the scenes using a platform headless retained fragment that intercepts Activity callbacks. You can use `Backstack` directly.

------------

However there is definitely an interesting (😞) race condition in regards to setting up a fragment factory, and initializing a Navigator instance. 

`super.onCreate()` recreates the `BackstackHost`, and by that time, the `fragmentFactory` must be set for proper re-initialization. In fact, by that time, for Fragments to be initialized with scoped services that have their states properly restored, an initialization state change must have been executed, which means `backstack.setup()` happened, and so did `backstack.setStateChanger()`.

------------

Internally, your state changer is wrapped with the `managedStateChanger` that actually executes the scoping-related changes. This is deferred because the active scope hierarchy wants to mimic the current active navigation history.

*Theoretically* it could be possible to force `backstack.setup()` to also eagerly construct a hierarchy, but I'm not sure it's a good idea to "handle state changes" while there is no state changer. 🤔 

------------

------------

In your case, a simple workaround would be to `backstack.setStateChanger(NoOpStateChanger())` where `NoOpStateChanger` would be

``` kotlin
class NoOpStateChanger: StateChanger {
    override fun handleStateChange(stateChange: StateChange, callback: StateChanger.Callback) {
        callback.stateChangeComplete()
    }
}
```

Before `super.onCreate()`, and then you can set a *real* fragment state changer on the Backstack where you normally would.

Setting a new state changer should trigger an initialization state change, and result in the state that you're looking for. 🤔

**Comment by Zhuinden** [comment]
@matejdro my outlined trick hack works as per https://github.com/matejdro/simple-stack-dagger-scoping-sample/pull/1

**Comment by matejdro** [comment]
Nice trick.
