### ISSUE TITLE
Ability to reuse created fragments in history

### ISSUE THREAD

**Issue by topnax** [Zhuinden/simple-stack#235]
Let's have a following fragment transactions: `A` =>  `B`  => `C (currently active)`.  Now imagine going back in the history, say we call `Navigator.backPress(context)` one time. The `B` fragment is at the top of the stack and should be recycled, it's `onCreateView` method should not be called. The current behavior is such that fragment `B` is now detached from the container activity and it's view is recreated and not reused, thus consuming unnecessary CPU time.

Would it be possible to recycle fragments in the history that were previously shown?

Could you provide any hints on how to change the `DefaultFragmentStateChanger` or implement it yourself? I think that it is one of the key features that every fragment state changer should implement in my opinion.

**Comment by topnax** [comment]
In quick thoughts: calling `setHistory()` should detach all fragments. Calling `goTo` and `replace` should behave as I have written.

**Comment by Zhuinden** [comment]
Hey,

This was actually thoroughly discussed in https://github.com/Zhuinden/simple-stack/issues/133#issuecomment-495859930 .

> The current behavior is such that fragment B is now detached from the container activity and **its view is recreated and not reused, thus consuming unnecessary CPU time.**

I fully agree, however using `show/hide` does not trigger `onStop/onStart` (thus could create unpredictable behavior when using LiveData), while using `setMaxLifecycle(STARTED)` destroys the view just like `attach/detach`.

As such, I cannot make it the default behavior, even though I theoretically agree with you.

Nonetheless, it is possible to customize the behavior to use `show/hide` instead of `attach/detach` through the following means:

``` kotlin
        fragmentStateChanger = object: DefaultFragmentStateChanger(supportFragmentManager, R.id.containerGameDetailsFragment) {
            override fun isNotShowing(fragment: Fragment): Boolean {
                return fragment.isHidden;
            }

            override fun startShowing(fragmentTransaction: FragmentTransaction, fragment: Fragment) {
                fragmentTransaction.show(fragment);
            }

            override fun stopShowing(fragmentTransaction: FragmentTransaction, fragment: Fragment) {
                fragmentTransaction.hide(fragment);
            }
        }
```

**Comment by Zhuinden** [comment]
With that, the currently available only alternative that retains the views (show/hide) is demonstrated, and this question is technically resolved.

Just beware that it doesn't alter the Fragment's lifecycle (and trigger onStop). And Fragments are currently unable to trigger onStop without also destroying their views. It's an unfortunate limitation of Fragments.
