### ISSUE TITLE
Multiple stacks + shared scope between different stacks

### ISSUE THREAD

**Issue by MFlisar** [Zhuinden/simple-stack#247]
Is that somehow possible? I found your example about bottom navigation + one stack per bottom navigation item. What I have is following:

* 1 activity with it's own stack
* n fragments (one for each bottom navigation item) with their own stacks
* 
Everything is set up based on your article [here](https://zhuinden.medium.com/creating-a-bottomnavigation-multi-stack-using-child-fragments-with-simple-stack-c73c1ca3bbd4)

Now I want that fragments inside different bottom navigation items can communicate with each other - actually like you do it in this [example](https://github.com/Zhuinden/simple-stack-tutorials/tree/93554f7000efe49fca39de7ca707eb6843a5eaf8/app/src/main/java/com/zhuinden/simplestacktutorials/steps/step_8).

The problem are the multiple stacks and I don't know how I can pass data between multiple stacks. Any ideas how this can be solved?

**Comment by Zhuinden** [comment]
Technically the only shared scope between the substacks hosted by the fragments are within the Activity-level backstack, so you'd most likely need to communicate through a shared parent in there, possibly using something like https://github.com/Zhuinden/event-emitter (or its [lifecycle-wrapper variant](https://github.com/Zhuinden/live-event)) so that they process the event when they come into view.

Please note that an EventEmitter does not persist its values across process death, so if such pending values are needed, I'd set them as a field (probably within a BehaviorRelay when using Rx) and save/restore it with Bundleable.

So technically, go through the parent if you need to talk across stacks, those are completely independent. 🤔

**Comment by Zhuinden** [comment]
Did this help answer the question?

**Comment by MFlisar** [comment]
I'm not sure how you access the `parentStack` or how you meant this...

But as I do manage the fragments manually inside the root view with the bottom sheet I simply pass on the root backstack to the `FragmentStackHostFragment` and then each fragment inside the `FragmentStackHostFragment` is able to access the root backstack as well.

**Comment by Zhuinden** [comment]
`parentStack` should be the same as `Fragment.backstack` which is the same as `Navigator.getBackstack(requireContext())` if the nesting level is 1

**Comment by MFlisar** [comment]
> But yeah, if you do see both, then it really is a matter of checking with `canFind`

Actually, I do know where the desired item is in, so I can directly use the correct backstack, But with your suggestion I don't even need to know this and I can use a "fullLookup" function like following inside the `FragmentStackHostFragment`:

    inline fun <reified T : Any> fullLookup(serviceTag: String = T::class.java.name): T {
        if (stackHost.backstack.canFind<T>()) {
            // return the item from local backstack
            return stackHost.backstack.lookup(serviceTag)
        } else {
            // fall back to global backstack and try to find it there
            return backstack.lookup(serviceTag)
        }
    }

Thanks for your feedback, it solved my problem

**Comment by Zhuinden** [comment]
Glad to hear it helped resolve your issue 🎉

**Comment by Zhuinden** [comment]
While I'm pretty sure this is effectively obsolete by now as it's been 2 years, but the feature was added directly to Simple-Stack as per https://github.com/Zhuinden/simple-stack/issues/239
