### ISSUE TITLE
Question: What is the purpose of RegistrationViewModel inside ServiceProvider in extension-compose-example?

### ISSUE THREAD

**Issue by ydhnwb** [Zhuinden/simple-stack#266]
I've read the documentation, your video about simple-stack on youtube and the example code at [extension-examples-compose](https://github.com/Zhuinden/simple-stack/blob/master/samples/advanced-samples/extensions-compose-example/src/main/java/com/zhuinden/simplestackextensionscomposesample/app/ServiceProvider.kt) like below:  

![image](https://user-images.githubusercontent.com/26734262/211478603-a0726300-6606-497b-972f-3c2e03b365e9.png)  

I don't know the purpose of adding "RegistrationViewModel" into it?
Is it because the RegistrationViewModel is used by tow fragment (CreateLoginCredentials and EnterProfileData) like below?  

![image](https://user-images.githubusercontent.com/26734262/211479543-fe429758-6f9e-47eb-b8b1-16f0038ef5dd.png)  

Is it the instance will cleared when the fragments who consume it with ScopeKey.Child get closed by backstack?  

![image](https://user-images.githubusercontent.com/26734262/211480553-64432a77-1d6c-40bd-a619-694cda3d27f1.png)  

![image](https://user-images.githubusercontent.com/26734262/211480831-3f64a698-3076-429a-b7b1-6046cd2fc2fe.png)

**Comment by Zhuinden** [comment]
Good questions! 

Theoretically I could have registered `RegisterViewModel` via `ScopeKey` from the first screen (i think it's `EnterProfileDataKey`), and you'd be able to see it on the second screen's Fragment via `by lazy { lookup<RegistrationViewModel>() }` as well. This is what [the video](https://www.youtube.com/watch?v=5ACcin1Z2HQ) calls implicit parents.

But in this sample I specifically used `ScopeKey.Child` (explicit parents) because it portrays how you can define a shared scope that is instantiated if *any* of the keys are added, and not just specifically the first step (oftentimes you have a ui flow to implement with multiple steps, and some are optional -- imagine getting a crash because the first step is no longer needed, only 2-3-4th  🤦)


> Is it because the RegistrationViewModel is used by tow fragment (CreateLoginCredentials and EnterProfileData) like below?

Yes, if you can't guarantee that a given key exists but "one of multiple keys" does, then if "one of the keys" is in the history, then the scope is kept alive.


> Is it the instance will cleared when the fragments who consume it with ScopeKey.Child get closed by backstack?

If there is no key that defines the scope as a parent, then it will be destroyed (`onServiceUnregistered()`).

**Comment by ydhnwb** [comment]
Ah I see, it's as simple as two fragments that implement ScopeKey.Child will try to lookup (potentially) same service by looking at it's TAG.

**Comment by Zhuinden** [comment]
Technically it's the key that implements `ScopeKey.Child` not the fragment, but yes, you can pull the service that you shared as many as you want.

The service provider class in the sample is to show that if you define a custom scope, then you'll need to pass a more customized class than just `DefaultServiceProvider`.

**Comment by ydhnwb** [comment]
It clears my head. Thanks
