### ISSUE TITLE
Convert all samples to AutoValue (and auto-parcel) for consistency in equals/hashcode/toString behavior + best practice

### ISSUE THREAD

**Issue by KennyGoers** [Zhuinden/simple-stack#41]
In the code for the sample application, there are potential issues around the storage of the keys. The code in FragmentStateManager uses a List<>.contains() to test if an item is in the path already, the Key where I can tell doesn't override "equals" to allow testing against the "tag" value instead of object equality. If this is expected then ignore please.

**Comment by Zhuinden** [comment]
If you mean `simple-stack-example-fragments`, then every "concrete" (in quotation marks) key in the sample is generated by AutoValue, which means `equals` and `hashCode` are generated by AutoValue based on the abstract field getters.

And same seems to be the case for the `simple-stack-flow-masterdetail-fragments`.

I think if there's a sample where this could be an issue, it's the newly added `mortar-sample` because that only checks against `instanceof` instead of true object equality. Maybe I should convert all samples to use AutoValue because nobody (hopefully) really writes this parcelable equals hashcode toString by hand anymore.

**Comment by Zhuinden** [comment]
I've changed all samples to use `auto-parcel`.

AutoValue generates equals/hashcode/toString in all cases.

To remove classes from being used in equals/hashCode, you can use https://github.com/REggar/auto-value-ignore-hash-equals library.

I think that should make behavior consistent. If you see any oddity though, please report.
