### ISSUE TITLE
Can I use this library easily with Data-binding mvvm-pattern?

### ISSUE THREAD

**Issue by fvermeulen** [Zhuinden/simple-stack#45]
Hey at first thanks for the good samples. I want to use your library, but till now I didn't found out if it is possible to switch the fragments easily in the viewmodels. Does your library support that? If not how would you solve this issue?

**Comment by Zhuinden** [comment]
Hi! By "switch fragments easily in viewmodels", do you mean that you would be able to call `backstack.goTo(OtherFragmentKey.create())` and navigate there, without having a need for fragment manager directly, or even creating Fragment directly?

Because if so, then the answer is **yes** - the backstack is typically managed by Activity (and handles navigation *inside the activity*, so fragments or views as per your choice), but it is the activity who handles the navigation itself, while you can call navigation methods on `backstack` elsewhere.

[You can see in MVP-fragments example that Presenter can call `backstack` methods and it is not android-specific](https://github.com/Zhuinden/simple-stack/blob/master/simple-stack-example-mvp-fragments/src/main/java/com/zhuinden/simplestackdemoexamplefragments/presentation/paths/tasks/TasksPresenter.java#L75-L77):

``` java
@Inject
Backstack backstack;

public void openTaskDetails(Task task) {
    backstack.goTo(TaskDetailKey.create(task.id()));
}
```

injected from this module

``` java
@Module
  public class NavigationModule {
  @Provides
  public Backstack backstack(BackstackHolder backstackHolder) {
     return backstackHolder.getBackstack();
  }
}
```

Hopefully that's what you meant and I could answer your question.

**Comment by fvermeulen** [comment]
nice brilliant thanks

**Comment by Zhuinden** [comment]
The trick with fragments is that I initialize the backstack (and set it as value of `BackstackHolder`) **before** calling `super.onCreate()`. That way the backstack is guaranteed to exist before Fragments are recreated by the system; this makes it work reliably.

The basic fragment example works in the same way:

``` java
    BackstackDelegate backstackDelegate;
    FragmentStateChanger fragmentStateChanger;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        backstackDelegate = new BackstackDelegate(null);
        backstackDelegate.onCreate(savedInstanceState,
                getLastCustomNonConfigurationInstance(),
                HistoryBuilder.single(HomeKey.create()));
        super.onCreate(savedInstanceState); // <-- called after calling backstackDelegate.onCreate()!

        ....
        fragmentStateChanger = new FragmentStateChanger(getSupportFragmentManager(), R.id.root);
        backstackDelegate.setStateChanger(this);
    }
```

[The basic fragment example contains everything needed to work with fragments + simple-stack](https://github.com/Zhuinden/simple-stack/blob/master/simple-stack-example-basic-fragment/src/main/java/com/zhuinden/navigationexamplefrag/MainActivity.java), if you have any further questions don't hesitate 😄

**Comment by fvermeulen** [comment]
Yeah one question I have :) 
For what do you need the 'key' classes. I saw you implemented the parceler there... 
I don't want to write for every fragment /activity a key class and thinking about writing an annotation in my kotlin code to generate the needed class for me. So I would set the layout Id to the annotation, but what's with the parceler then

**Comment by Zhuinden** [comment]
Okay, so internally the library keeps the objects you pass in in a list, and it'll apply the registered `KeyParceler` to make it become Parcelable (so that it can be saved to Bundle then restored from Bundle if needed). Default behavior assumes you are using Parcelable classes. 

So anything that will eventually be Parcelable somehow, even a String, would work. But then passing parameters gets tricky, and I think using an auto-value parcelable or a data class with PaperParcel is easier than implementing Uri matching. 

Other similar libraries also tell you to create a `___Screen` class that serves the same functionality, determining which class to show, and to store it in History. 

But if you're still not sold on making a key, think of it as the initial parameters you would need to create an Activity or a Fragment - so this is what contains initial parameters, akin to Intent Extras or Fragments Arguments. 

The key is parcelable, so it can be passed to the fragment as arguments. Then all additional parameters become typed and named. No more `static final` constants for your arguments bundle! 

Personally I create a Key for each fragment/view, and it makes passing parameters much easier.

**Comment by Zhuinden** [comment]
So if you ask me, making a Key for each fragment is a *recommendation*, because it makes navigation super-easy, and you get typed initial parameters.

**Comment by Zhuinden** [comment]
If you want to ditch both keys and StateBundle, you'd need something like [this approach (matching uri and obtaining params from it)](https://github.com/trikita/android-router/blob/master/library/src/main/java/trikita/router/Utils.java)

**Comment by fvermeulen** [comment]
Sure I think it makes sense to create a key-class. I will test around to auto generate the class for me. Will try to create an annotation, that does the job creating the class

**Comment by Zhuinden** [comment]
A possibility would be adding a template. I've heard Android Studio can be extended with adding new types of things it can auto-generate. I think AutoValue makes it easy to create either way, either Auto-Parcel or PaperParcel are good options.

**Comment by Zhuinden** [comment]
Have you found an approach that you like? 😄

**Comment by fvermeulen** [comment]
Hey do I need to create for every view element a custom class?

**Comment by Zhuinden** [comment]
Only if you use custom views. But if you use custom views, then think of it like creating a new Fragment class for each fragment, which honestly does make sense. 

If you use Fragments, then no, just use Views and layout xml as you normally would.

**Comment by Zhuinden** [comment]
With addition of the [Google Architecture Blueprints: MVVM-Databinding](https://github.com/googlesamples/android-architecture/tree/4c41b4a163e5698185501a2232c7988024ab0383/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp) sample as [Simple-Stack MVVM Example](https://github.com/Zhuinden/simple-stack/tree/d0dc7f7dbb7c255fdd48cc9b9f169b299b2f1d15/simple-stack-example-mvvm-fragments), I am closing this.
