### ISSUE TITLE
going back in multistack

### ISSUE THREAD

**Issue by matyj** [Zhuinden/simple-stack#49]
Hi, 
I'm using your multistack implementation from sample in my app. My problem is, that I've got a screen that is accessible from almost every stack (the multistack is implemented in bottom navigation tabs if it's important). From this screen I can go to the same screen, in such case that I've got project details and similiar projects inside, so when I click on one of the similiar projects, I go to the same screen as the previous one. Going further, when clicking back, I want to omit all the previous project details screens and go back to the screen, in which I've chosen the first project detail. My question is: is there a way to do that in a simple way different from setting stack history explicitly? Another question is: is there any simple way to push some parameters when going back in stack? I want to have behaviour like "onActivityResult".

**Comment by Zhuinden** [comment]
> My question is: is there a way to do that in a simple way different from setting stack history explicitly?

I think you're most likely looking for `HistoryBuilder.removeUntil()` (which keeps the key you specified, but removes all elements from top to that element), but you will need to set the stack history explicitly with `setHistory(newHistory, Direction.BACKWARD)`.

So something like, 

``` java
backstack.setHistory(HistoryBuilder.from(backstack).removeUntil(KeyToGoTo.create()).build(), Direction.BACKWARD);
```

> is there any simple way to push some parameters when going back in stack? I want to have behaviour like "onActivityResult".

Now that's a bit tricky because there are two ways:

1.) either replace the key in the stack with a version of it that has the parameter set, for example you could add a `StateBundle` to the key (although you should most likely extend it so that `hashCode()`/`equals()` does not make it think it is a different object)

2.) create a ["MessageQueue"](https://github.com/Zhuinden/simple-stack/blob/master/simple-stack-example-mvp-view/src/main/java/com/zhuinden/simplestackdemoexamplemvp/util/MessageQueue.java) that you check for pending messages when your view is ready, and identify if the given view has received messages from other views

As you can see, my example used the second option, although it's a bit rudimentary.

**Comment by matyj** [comment]
Thank you so much!

**Comment by Zhuinden** [comment]
I know it's probably irrelevant at this point, but with the revised `Backstack` (which was "BackstackManager" previously after 1.1.0) implementation, I could update the Multistack sample like so:

https://github.com/Zhuinden/simple-stack/blob/f28fcae66287dbb92faefdc905cd2901dd3e7e8d/simple-stack-example-multistack-view/src/main/java/com/zhuinden/simplestackdemomultistack/core/navigation/Multistack.kt

Which is much more convenient to use than BackstackDelegate + setPersistenceTag.
