### ISSUE TITLE
Add ability to define "Redirect" where a given state change is transformed into another one, before the actual navigation occurs

### ISSUE THREAD

**Issue by Zhuinden** [Zhuinden/simple-stack#64]
Copy of https://github.com/square/flow/compare/square:f30c595...square:b9a5eb2 from https://github.com/square/flow/issues/191

Although I really don't see its use, so... maybe?

**Comment by Zhuinden** [comment]
Nobody said anything about this, but I've attended a conference where the guy had his own mini-framework thing that is so open-source that I couldn't find it anywhere, **but** he had the concept of `NavigationInterceptor`s which essentially did something like this:

----

Instead of

    // this is splash screen
    Key key = userManager.isLoggedIn() ? MainKey.create() : LoginKey.create();
        backstack.replaceTop(key, StateChange.FORWARD);

he had something like

    backstack.replaceTop(MainKey.create());

and an interceptor

    public StateChange intercept(StateChange stateChange) {
        Key top = stateChange.topNewState();
        if(top instanceof MainKey && !userManager.isLoggedIn()) {
             return new StateChange(LoginKey.create(), stateChange.direction());
        }
        return stateChange;
    }

I cannot decide if this is needed, but...

**Comment by Zhuinden** [comment]
Although who said a transformation should be synchronous process?

Should probably be callback-based like a state change.

**Comment by Zhuinden** [comment]
Today I've encountered a use-case where this is handy.

Requirement: "add an interstitial view that fades out into the other view when `this specific view` is opened".

With a state change transform, it can be checked that if the new top is the key for  `this specific view`, then the specific view is replace-top'd with the interstitial, and the interstitial will handle the replace-toping to the proper target.

**Comment by Zhuinden** [comment]
However, for this, I need to rework the calculation of history to not be immediate.

**Comment by beyama** [comment]
Just wanted to give some feedback here because I encountered a problem where I thought it would be nice to have an asynchronous interceptor in SimpleStack but then solved it within the `StateChanger` and liked the solution more.

I've used SimpleStack for a client project.
We had two screens which required authentication for some of the data to show dependent on metadata we sometimes had in memory and sometimes had to load from a network service (so the check could have been synchron or asynchron).
The app was simply view based and we checked the condition in the `StateChanger` and for cases where authentication was required we just loaded the login view instead of the actual target. After authentication we could simply reload the current top state key `backstack.top<StateKey>()?.let { backstack.replaceTop(it, StateChange.REPLACE) }` to open the original target.

**Comment by Zhuinden** [comment]
BTW in Angular, you can implement a "guard" which can return both a boolean, or an `Observable<Boolean>`.

The way it works is that if you return false (sync/async) then the navigation command is aborted. 

In the guard, you can however also call `router.navigate` before `return false`, and it will actually go over *there*.

Hrmm... It'd be tricky to know what was added by the guard, and what needs be aborted on `false`.

**Comment by Zhuinden** [comment]
The right name is `Guard`.

**Comment by Zhuinden** [comment]
Actually I should call it a `Redirect`. 🤔 

Also I'll need this to prevent some possible illegal states. I guess this is needed after all.
