### ISSUE TITLE
Project modularization

### ISSUE THREAD

**Issue by gumil** [Zhuinden/simple-stack#66]
It would be nice to have a way to use fragments using Navigator

**Comment by Zhuinden** [comment]
It is impossible because I cannot guarantee the recreation order of fragments after process death.

**Comment by Zhuinden** [comment]
I'll try it out with deferred init and see what happens.

**Comment by gumil** [comment]
maybe a DefaultStateChanger for Fragments is enough?

**Comment by Zhuinden** [comment]
There is a bit more configuration required for Fragments than for View, because I'd have to provide a fragment you need to inherit from. Either to have the key in the arguments, or maybe even to bind it into the view hierarchy  in view inflation in onCreateView`.

Either way, I'd have to modularize the project and have the core, the navigator support, and a fragment support component.

Not a bad idea though, if I get past the intimidation of setting up multi-project for jitpack release

**Comment by gumil** [comment]
Any updates on this? I might also try and work on this. I'll see what I can do

**Comment by Zhuinden** [comment]
No I've been super-busy and this would bring 2.0 with it.

**Comment by gumil** [comment]
So far I didn't have any problems while using this:
```
Navigator.configure()
                .setStateChanger(FragmentStateChanger(supportFragmentManager, R.id.fragmentContainer))
                .setShouldPersistContainerChild(false)
                .install(this, fragmentContainer, HistoryBuilder.single(Key()))
```

I'll give an update if something needs to be done more.

**Comment by Zhuinden** [comment]
@gumil if there can be an issue with it, it's after process death.

You can verify process death behavior by putting your app in background with HOME, press "Terminate application" button in Android Studio (it's a Red X in the logcat tab), then restart your app in launcher.

If you get unpredictable behavior, then it doesn't work well.

**Comment by Zhuinden** [comment]
1.) navigator CAN be used with Fragments, although it's not possible if you use ScopedServices + FragmentFactory.

Otherwise, it works fine. 

2.) this would introduce a lot of complexity for maintenance so it won't happen. 🤔
