### ISSUE TITLE
How do I know if there is a fragment from savedInstanceState?

### ISSUE THREAD

**Issue by dev-JE02** [Zhuinden/simple-stack#73]
Right now I have this in my activity's onCreate:

```
backstackDelegate.onCreate(savedInstanceState,
                getLastCustomNonConfigurationInstance(),
HistoryBuilder.single(HomeKey.create()));
```

But when the application is restored from instanceState, it has the Home Fragment above whatever fragment the activity was killed with. What can I do to prevent this?

**Comment by Zhuinden** [comment]
The only way the key is not restored properly is if you didn't call `registerForLifecycleCallbacks(this)` after calling `onCreate` on the backstack delegate. See the [basic fragment example](https://github.com/Zhuinden/simple-stack/blob/f1dc9ffa24d2e44400e1ea22b9d16199de24ef1a/simple-stack-example-basic-fragment/src/main/java/com/zhuinden/navigationexamplefrag/MainActivity.java#L42).

 `registerForLifecycleCallbacks` is actually a short-hand that allows you to not have to manually call `onPause()`/`onResume()`/`onSaveInstanceState()`/`onDestroy()` on the BackstackDelegate. The reason for having these two options is because the library was written to be backwards compatible to even before API 14, and the `register*` method relies on `Application.ActivityLifecycleCallbacks` internally.

-----

Generally you only need to override `onCreate()` (of course), `onRetainCustomNonConfigurationInstance()`, and handle the back press in `onBackPressed()`.

**Comment by dev-JE02** [comment]
I already called `registerForLifecycleCallbacks(mActivity)` after onCreate actually

**Comment by Zhuinden** [comment]
...huh. Do you call `backstackDelegate.onCreate()` before `super.onCreate()`?

**Comment by dev-JE02** [comment]
In my abstraction, `super.onCreate()` is being called before `backstackDelegate.onCreate`

**Comment by Zhuinden** [comment]
Technically I started thinking about it and that shouldn't cause any trouble.

The real question is the fragment tag

**Comment by dev-JE02** [comment]
I copied the BaseKey from the simple fragment example project actually and this is what I have here

```
public abstract class BaseKey {
    public String getFragmentTag() {
        return getClass().getName();
    }

    public final BaseFragment newFragment() {
        BaseFragment fragment = createFragment();
        Bundle bundle = fragment.getArguments();
        if (bundle == null) {
            bundle = new Bundle();
        }
        bundle.putParcelable("KEY", Parcels.wrap(this));
        fragment.setArguments(bundle);
        return fragment;
    }

    protected abstract BaseFragment createFragment();
}
```

**Comment by dev-JE02** [comment]
I think the issue is not about retrieving the right fragments, it actually does retrieve the last fragment displayed before the activity is destroyed. The problem is that the initialKey I have in onCreate is either also overlaid on top of that fragment, or below it

**Comment by dev-JE02** [comment]
Sorry github is weird, I just read your full comments. Github concatenated and showed only the first lines. I'm pasting my initialization here:

```
backstackDelegate = new BackstackDelegate(null);
        backstackDelegate.onCreate(savedInstanceState,
                mActivity.getLastCustomNonConfigurationInstance(),
                HistoryBuilder.single(DashboardKey.create()));
        backstackDelegate.registerForLifecycleCallbacks(mActivity);

        fragmentStateChanger = new FragmentStateChanger(mActivity.getSupportFragmentManager(), R.id.container);
        backstackDelegate.setStateChanger((stateChange, completionCallback) -> {
            if (stateChange.topNewState().equals(stateChange.topPreviousState())) {
                completionCallback.stateChangeComplete();
                return;
            }
            fragmentStateChanger.handleStateChange(stateChange);
            completionCallback.stateChangeComplete();
        });
```

**Comment by dev-JE02** [comment]
I can send you a screenshot via email to show you what happens in the layout

**Comment by Zhuinden** [comment]
Okay, so the behavior says that if keys are restored from saved instance state, then that will be used in the initialization state change, and the initial history you provide will be ignored. 

Do your keys implement hashCode/equals properly? I use autovalue in the samples so that's a given for me, but not for you.

**Comment by Zhuinden** [comment]
If you have complete sample code for where the error occurs (state changer, key, activity code) then I can figure it out.

**Comment by Zhuinden** [comment]
Any luck? Theoretically, the state changer I have in the examples tries to check if the fragment is already added, and doesn't add it again if it's already added

**Comment by Zhuinden** [comment]
There was one time when I ended up with multiple instances of the same fragment, and what happened was that I was accidentally adding the same fragment twice for the same tag in the same transaction.

**Comment by dev-JE02** [comment]
> Okay, so the behavior says that if keys are restored from saved instance state, then that will be used in the initialization state change, and the initial history you provide will be ignored.
> 
> Do your keys implement hashCode/equals properly? I use autovalue in the samples so that's a given for me, but not for you.

I think this is my problem. I'm not using equals and hashcode in my keys. I'll try using autovalue then I'll let you know!

**Comment by Zhuinden** [comment]
So, did it work?

It should work. It honestly always worked for me.

**Comment by Zhuinden** [comment]
I'll just go with yes.

After the fragments are re-created, they are accessible via fragment tag, generally. Using fragments is specifically tricky in that `super.onCreate()` recreates them after process-death, so that is why I tend to initialize backstackDelegate _before_ `super.onCreate()`, and then set the state changer once everything is set up.

This makes it so that the history represents what the fragment manager will be restored as.

Anyways, equals/hashCode is required.
