### ISSUE TITLE
Exchange data between multiple views

### ISSUE THREAD

**Issue by LinArcX** [Zhuinden/simple-stack#77]
Hi @Zhuinden .
I want to implement single-activity/multi-view design. but there is an issue.
i'm working on [this](https://github.com/Zhuinden/simple-stack/tree/master/simple-stack-example-basic-view) sample and want to extend its functionality like allowing "exchange data in deep hierarchy of views".
For example in home view, i want to go to view1, then go to view2, then go to view3 and in all these steps, i want to carry some data.(like list, string, object or whatever)
how do this job?
I tried to use [this idea](https://github.com/antoniolg/androidmvp/blob/master/app/src/main/java/com/antonioleiva/mvpexample/app/main/FindItemsInteractor.java) for exchange data, but when the hirarchy is deep, This method does not work!

**Comment by Zhuinden** [comment]
For simple cases where View A needs to communicate with View B, I used [this `MessageQueue` class](https://github.com/Zhuinden/simple-stack/blob/8542759bfd5f82c8998b9b24ded9930c8a156674/simple-stack-example-mvp-view/src/main/java/com/zhuinden/simplestackdemoexamplemvp/util/MessageQueue.java) where any key can push any object to any "target", and the "target" will check the queue if they've received anything.

Technically it's like `startActivityForResult` but without intents.

------

In your case however, if your data is shared like that, then you should use a shared scope for the views, and put the data into an observable container thing that you can subscribe to for changes, so that each view will always request latest data.

That's the theoretical solution, anyways. Then you of course need to figure out 

You'd have this same issue with sharing data across fragments (or even worse, between activities!) so the same rules apply in this regard.

----

My attempted solution back in the day was the [ServiceTree](https://github.com/Zhuinden/service-tree) library, but setting that up is a bit harder than just managing a singleton. I never had a need for that in production, because we just wrote everything to DB and subscribed for changes of the DB, and that's how we shared data.

**Comment by Zhuinden** [comment]
Did any proposals help?

**Comment by LinArcX** [comment]
Thanks for your greate offers. I read them all, but I got a new idea. The idea is that:
passing data to other view, when we want to navigate to it.
To achieve this, i overload the constructor to accept Bundle or Parcelable. for example in the View2(Key)There must be another constructor:
```
    private static Bundle mBundle;

    public Bundle getBundle(){
        return mBundle;
    }

    public static OtherKey create() {
        return new AutoValue_OtherKey();
    }

    public static OtherKey create(Bundle bundle){
        mBundle = bundle;
        return new AutoValue_OtherKey();
    }
```
and in View2(view), you can get the desired method:

  ```
  @Override
    protected void onFinishInflate() {
        super.onFinishInflate();
        ButterKnife.bind(this);
        loadMessage();
    }

    private void loadMessage() {
        otherKey = Backstack.getKey(mContext);
        mTextMessage.setText(otherKey.getBundle().getString("Greeting"));
    }
```

**Comment by Zhuinden** [comment]
Ah yeah, personally when I had to send data to another screen, I just added the ID  of the object as a field in the target screen key, and sent it over on navigation.

Like, `backstack.goTo(DetailKey.create(detailId));`

Then cache can be managed by something singleton which you can subscribe to for changes too. 

Not sure why that Bundle is static, I can only imagine that would cause bugs. If you really don't know what you could be sending, then `StateBundle` is a valid option - because it implements hashCode / equals properly, unlike a Bundle

**Comment by Zhuinden** [comment]
(StateBundle is a transitive dependency of Simple-Stack, so you can use it out of the box pretty much)

**Comment by Zhuinden** [comment]
So yeah, send a StateBundle instead of Bundle, then equals/hashCode will work

**Comment by Zhuinden** [comment]
Since then, there is also a "guide" or "tutorial" sample that shows how this would be done with simple-stack.

https://github.com/Zhuinden/simple-stack-tutorials/blob/c079223032b37b21f0549548d2b68e9a6e4caa62/app/src/main/java/com/zhuinden/simplestacktutorials/steps/step_7/features/registration/RegistrationViewModel.kt#L12
